"""
Patch History Store  (Phase 3D.1)
===================================
In-memory store for patch generation history.  Every patch generation event
is recorded as a ``PatchHistoryEntry`` for audit, debugging, and future
continual-learning support.

Capabilities
------------
- ``record()``            — Append a new history entry.
- ``get_by_bug_id()``     — Retrieve all entries for a bug.
- ``get_by_category()``   — Retrieve entries by repair category.
- ``get_recent()``        — Latest N entries (most recent first).
- ``mark_accepted()``     — Mark a candidate as accepted by a developer.
- ``export()``            — Serialise the entire history to JSON bytes.
- ``import_from_json()``  — Restore history from exported JSON.
- ``clear()``             — Wipe the store (primarily for tests).
- ``stats()``             — Return aggregate statistics.

Design invariants
-----------------
- The store is thread-safe: all mutations use a threading.Lock.
- Entries are stored in insertion order; retrieval preserves order unless
  otherwise specified.
- The store is intentionally in-memory for Phase 3D.1; Phase 3D.2 will
  replace with a persistent backend (SQLite/Postgres) using the same
  interface.
- ``export()`` / ``import_from_json()`` round-trip losslessly.
"""
from __future__ import annotations

import json
import logging
import threading
from typing import Any, Dict, List, Optional

from backend.core.patch_generation.patch_models import (
    PatchHistoryEntry,
    RepairCategory,
)

logger = logging.getLogger("backend.patch_generation.patch_history")


class PatchHistoryStore:
    """
    Thread-safe in-memory store for ``PatchHistoryEntry`` records.

    Usage
    -----
        store = PatchHistoryStore()
        store.record(entry)
        recent = store.get_recent(n=10)
    """

    def __init__(self) -> None:
        self._entries: List[PatchHistoryEntry] = []
        self._lock    = threading.Lock()

    # ------------------------------------------------------------------
    # Write operations
    # ------------------------------------------------------------------

    def record(self, entry: PatchHistoryEntry) -> None:
        """Append *entry* to the history store."""
        with self._lock:
            self._entries.append(entry)
        logger.debug(
            "PatchHistoryStore: recorded entry '%s' for bug '%s' (category=%s).",
            entry.entry_id,
            entry.bug_id,
            entry.repair_category.value,
        )

    def mark_accepted(
        self,
        entry_id:          str,
        accepted_patch_id: str,
    ) -> bool:
        """
        Mark the accepted patch candidate for a history entry.

        Parameters
        ----------
        entry_id          : ID of the ``PatchHistoryEntry`` to update.
        accepted_patch_id : ID of the accepted ``PatchCandidate``.

        Returns
        -------
        True if the entry was found and updated, False otherwise.
        """
        with self._lock:
            for entry in self._entries:
                if entry.entry_id == entry_id:
                    entry.accepted_patch_id = accepted_patch_id
                    logger.info(
                        "PatchHistoryStore: entry '%s' marked accepted (patch='%s').",
                        entry_id,
                        accepted_patch_id,
                    )
                    return True
        logger.warning(
            "PatchHistoryStore.mark_accepted: entry '%s' not found.", entry_id
        )
        return False

    def clear(self) -> None:
        """Remove all entries (primarily for testing)."""
        with self._lock:
            self._entries.clear()
        logger.debug("PatchHistoryStore: cleared.")

    # ------------------------------------------------------------------
    # Read operations
    # ------------------------------------------------------------------

    def get_by_bug_id(self, bug_id: str) -> List[PatchHistoryEntry]:
        """Return all entries for *bug_id*, in insertion order."""
        with self._lock:
            return [e for e in self._entries if e.bug_id == bug_id]

    def get_by_category(
        self,
        category: RepairCategory,
    ) -> List[PatchHistoryEntry]:
        """Return all entries with *category*, in insertion order."""
        with self._lock:
            return [e for e in self._entries if e.repair_category == category]

    def get_by_provider(self, provider: str) -> List[PatchHistoryEntry]:
        """Return all entries generated by *provider*."""
        with self._lock:
            return [e for e in self._entries if e.provider == provider]

    def get_recent(self, n: int = 20) -> List[PatchHistoryEntry]:
        """Return the *n* most recently recorded entries."""
        with self._lock:
            return list(reversed(self._entries[-n:]))

    def get_accepted(self) -> List[PatchHistoryEntry]:
        """Return all entries where a patch has been accepted."""
        with self._lock:
            return [e for e in self._entries if e.accepted_patch_id is not None]

    def all(self) -> List[PatchHistoryEntry]:
        """Return a snapshot of all entries in insertion order."""
        with self._lock:
            return list(self._entries)

    def __len__(self) -> int:
        with self._lock:
            return len(self._entries)

    # ------------------------------------------------------------------
    # Aggregate statistics
    # ------------------------------------------------------------------

    def stats(self) -> Dict[str, Any]:
        """
        Return aggregate statistics over the full history.

        Returns
        -------
        Dict with keys: total, accepted_count, by_category, by_provider,
        avg_generation_time_ms, avg_candidate_count.
        """
        with self._lock:
            entries = list(self._entries)

        total    = len(entries)
        accepted = sum(1 for e in entries if e.accepted_patch_id)

        by_cat: Dict[str, int] = {}
        by_prov: Dict[str, int] = {}
        total_time = 0.0
        total_cands = 0

        for e in entries:
            by_cat[e.repair_category.value]  = by_cat.get(e.repair_category.value,  0) + 1
            by_prov[e.provider]              = by_prov.get(e.provider,              0) + 1
            total_time  += e.generation_time_ms
            total_cands += e.candidate_count

        return {
            "total":                  total,
            "accepted_count":         accepted,
            "by_category":            by_cat,
            "by_provider":            by_prov,
            "avg_generation_time_ms": round(total_time  / total, 2) if total else 0.0,
            "avg_candidate_count":    round(total_cands / total, 2) if total else 0.0,
        }

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def export(self) -> bytes:
        """
        Serialise the full history to JSON bytes.

        The format is a top-level dict ``{"version": "3D.1", "entries": [...]}``
        where each entry is the Pydantic model_dump() representation.
        """
        with self._lock:
            payload = {
                "version": "3D.1",
                "entries": [e.model_dump() for e in self._entries],
            }
        data = json.dumps(payload, indent=2, default=str)
        logger.info(
            "PatchHistoryStore.export: serialised %d entries.", len(self._entries)
        )
        return data.encode("utf-8")

    @classmethod
    def import_from_json(cls, data: bytes) -> "PatchHistoryStore":
        """
        Create a new ``PatchHistoryStore`` populated from exported JSON bytes.

        Parameters
        ----------
        data : JSON bytes as produced by ``export()``.
        """
        store = cls()
        try:
            payload  = json.loads(data.decode("utf-8"))
            entries  = payload.get("entries", [])
            for raw in entries:
                entry = PatchHistoryEntry(**raw)
                store._entries.append(entry)
            logger.info(
                "PatchHistoryStore.import_from_json: loaded %d entries.", len(store._entries)
            )
        except Exception as exc:
            logger.error(
                "PatchHistoryStore.import_from_json: failed to load — %s", exc
            )
        return store
